# Indexing in numpy arrays

In [1]:
import numpy as np

1d array

In [2]:
x = np.array([10,11,12,13,14,15,155])
print(x[5])

15


In [3]:
print(x[4])

14


In [4]:
print(x[-1])

155


In [5]:
print(x[-5])

12


2d array

In [6]:
x = np.array([[11,12], [13,14]])
print(x[1,0])

13


In [7]:
print(x[0,1])

12


In [8]:
x = np.array([[4,5,6],
              [10,11,12],
              [13,14,15]])
print(x[1,2])

12


In [9]:
print(x[2,1])

14


In [10]:
print(x[0,0])

4


3d array

In [11]:
b = np.array([[[11,12],
               [13,14]],
               [[15,16],
               [17,18]]])
print(b)
print(b[1,1,0])

[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]
17


In [12]:
print(b[0,1,0])

13


In [13]:
print(b[1,0,1])

16


In [14]:
c = np.array([[[3,6,9],
               [12,15,18],
               [1,5,7]]])
print(c)
print(c.ndim)

[[[ 3  6  9]
  [12 15 18]
  [ 1  5  7]]]
3


In [15]:
print(c[0,1,2])

18


In [16]:
print(c[0,2,0])

1


5d array

In [17]:
a = np.array([[[[[1,2,3],
                 [4,5,6],
                 [7,8,9]]]]])
print(a)
print(a.ndim)

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]]]]
5


In [18]:
print(a[0,0,0,1,1])

5


In [19]:
print(a[0,0,0,2,1])

8


# Slicing of Numpy array

1d array

In [20]:
a = np.array([11,12,13,14,15,16,17,18,19])
print(a[2:7])

[13 14 15 16 17]


In [21]:
print(a[2:7:2])

[13 15 17]


In [22]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0:5])

[1 2 3 4 5]


In [23]:
print(a[:])

[1 2 3 4 5 6 7 8 9]


In [24]:
print(a[::-1])

[9 8 7 6 5 4 3 2 1]


In [25]:
b = np.array([25,27,29,34,56,89,43])
print(b[3:5])

[34 56]


# Slicing in 2d array

In [26]:
c = np.array([[10,11,12,13,14,15],[20,21,22,23,24,25]])
print(c)
print(c[1,1:4])

[[10 11 12 13 14 15]
 [20 21 22 23 24 25]]
[21 22 23]


In [27]:
print(c[0,1:4])

[11 12 13]


In [28]:
print(c[1,::-1])

[25 24 23 22 21 20]


# Slicing in 3d array

In [29]:
a = np.array([[[1,2,5,6,7],[4,7,3,9,10],[11,14,15,16,17]]])
print(a)

[[[ 1  2  5  6  7]
  [ 4  7  3  9 10]
  [11 14 15 16 17]]]


In [30]:
print(a[0,1,1:4])

[7 3 9]


In [31]:
print(a[0,2,1:5])

[14 15 16 17]


In [32]:
print(a[0,1,::-1])

[10  9  3  7  4]


# Joining Numpy array

In [33]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [34]:
arr1 = np.array([[11,12,13],[31,32,33]])
arr2 = np.array([[14,15,16],[61,60,59]])
arr = np.concatenate((arr1,arr2), axis=0)
print(arr)

[[11 12 13]
 [31 32 33]
 [14 15 16]
 [61 60 59]]


In [35]:
arr1 = np.array([[11,12,13],[31,32,33]])
arr2 = np.array([[14,15,16],[61,60,59]])
arr = np.concatenate((arr1,arr2), axis=1)
print(arr)

[[11 12 13 14 15 16]
 [31 32 33 61 60 59]]


# Splitting Numpy array

splitting the array in 3 parts

In [36]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)
print(type(newarr))

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>


splitting the array in 4 parts

In [37]:
arr = np.array([[1,2],[3,4],[5,6]])
newarr = np.array_split(arr,4,axis=1)
print(newarr)

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32), array([], shape=(3, 0), dtype=int32)]


# Search array

In [38]:
a = np.array([1,2,3,4,5,3,4,2,6,8,9])
x = np.where(a==3)
print(x)

(array([2, 5], dtype=int64),)


In [39]:
a = np.array([1,2,3,4,5,3,4,2,6,8,9])
x = np.where(a%2==0)
print(x)

(array([1, 3, 6, 7, 8, 9], dtype=int64),)


# search sorted array

In [40]:
z = np.array([11,12,14,15,161,18,19])
x = np.searchsorted(z,15)
print(x)

3


In [41]:
z = np.array([11,12,14,15,161,18,19])
x = np.searchsorted(z,18,side='right')
print(x)

6


In [42]:
p = np.array([21,22,23,24,43,44,45])
n = np.searchsorted(p,[25,28,30])
print(n)

[4 4 4]


# Sorting array

In [43]:
a = np.array([12,34,5,4,345,567,45,-1,-45,-65,76])
print(np.sort(a))

[-65 -45  -1   4   5  12  34  45  76 345 567]


In [44]:
b = np.array(['o','k','v','l','r','q','t','e','a'])
print(np.sort(b))

['a' 'e' 'k' 'l' 'o' 'q' 'r' 't' 'v']


In [45]:
a = np.array([[48,45,12],[13,23,2],[-5,98,87]])
print(a)
print(np.sort(a))

[[48 45 12]
 [13 23  2]
 [-5 98 87]]
[[12 45 48]
 [ 2 13 23]
 [-5 87 98]]


In [46]:
x = np.array([[[14,18,-9],[-2,36,16],[56,-100,-50]]])
print(x)
print(np.sort(x))

[[[  14   18   -9]
  [  -2   36   16]
  [  56 -100  -50]]]
[[[  -9   14   18]
  [  -2   16   36]
  [-100  -50   56]]]


# Filter array

In [47]:
a = np.array([12,13,1,5,67,8,90])
f = [ True, False, False, True, True, False, True]
b = a[f]
print(b)

[12  5 67 90]


# Shuffle Function

In [48]:
k = np.array([12,34,5,66,7,78,9,90,32,21])
print("The array is:",k)
np.random.shuffle(k)
print("now the shuffled array is:",k)

The array is: [12 34  5 66  7 78  9 90 32 21]
now the shuffled array is: [ 5 21 12 78 66  9 34 90 32  7]


# Unique Function

In [49]:
k = np.array([12,23,44,556,5,343,34,2,56,78,45,23,56,23,12,34,2,12,1])
print(k)
x = np.unique(k)
print(x)

[ 12  23  44 556   5 343  34   2  56  78  45  23  56  23  12  34   2  12
   1]
[  1   2   5  12  23  34  44  45  56  78 343 556]


In [50]:
k = np.array([12,23,44,556,5,343,34,2,56,78,45,23,56,23,12,34,2,12,1])
print(k)
x = np.unique(k,return_index = True)
print(x)

[ 12  23  44 556   5 343  34   2  56  78  45  23  56  23  12  34   2  12
   1]
(array([  1,   2,   5,  12,  23,  34,  44,  45,  56,  78, 343, 556]), array([18,  7,  4,  0,  1,  6,  2, 10,  8,  9,  5,  3], dtype=int64))


In [51]:
k = np.array([12,23,44,556,5,343,34,2,56,78,45,23,56,23,12,34,2,12,1])
print(k)
x = np.unique(k,return_index = True, return_counts = True)
print(x)

[ 12  23  44 556   5 343  34   2  56  78  45  23  56  23  12  34   2  12
   1]
(array([  1,   2,   5,  12,  23,  34,  44,  45,  56,  78, 343, 556]), array([18,  7,  4,  0,  1,  6,  2, 10,  8,  9,  5,  3], dtype=int64), array([1, 2, 1, 3, 3, 2, 1, 1, 2, 1, 1, 1], dtype=int64))


# Resize 

In [52]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.resize(a,(3,2))
print(b)

[[1 2]
 [3 4]
 [5 6]]


# Insert Function

In [53]:
n = np.array([1,2,3,4,5,6,7,8,9])
v = np.insert(n,3,200)
print(v)

[  1   2   3 200   4   5   6   7   8   9]


In [54]:
n = np.array([1,2,3,4,5,6,7,8,9])
v = np.insert(n,(3,4,5),(20,40,50))
print(v)

[ 1  2  3 20  4 40  5 50  6  7  8  9]


In [55]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])
v = np.insert(n,3,25,axis=1)
print(v)

[[ 1  2  3 25]
 [ 4  5  6 25]
 [ 7  8  9 25]]


In [56]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])
v = np.insert(n,3,21,axis=0)
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [21 21 21]]


In [57]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])
v = np.insert(n,3,[21,23,24],axis=0)
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [21 23 24]]


# append

In [58]:
a = np.array([12,13,14])
x = np.append(a,1.5)
print(x)

[12.  13.  14.   1.5]


In [59]:
x = np.array([[2,7,8,9,1],[4,3,6,12,14]])
m = np.append(x, [[-4,-5,-6,-7,-8]], axis=0)
print(m)

[[ 2  7  8  9  1]
 [ 4  3  6 12 14]
 [-4 -5 -6 -7 -8]]


# Delete Function

In [64]:
a = np.array([12,13,15,56,89])
d = np.delete(a,[1])
print(d)

[12 15 56 89]


In [66]:
x = np.array([[11,12,13],[31,32,33]])
y = np.delete(x,1, axis=0)
print(x)
print()
print(y)

[[11 12 13]
 [31 32 33]]

[[11 12 13]]
