# Matrix

In [1]:
import numpy as np

In [2]:
a = np.matrix([[1,2,3],[1,2,3]])
print(a)
print(type(a))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [3]:
b = np.array([[1,2,3],[1,2,3]])
print(b)
print(type(b))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


# Arithmetic Operations in matrix

In [4]:
print("We are talking about matrix")
a = np.matrix([[1,2,3],[1,2,3]])
c = np.matrix([[4,5,6],[4,5,6]])
print(a)
print()
print(c)
print(a+c)
print("We are talking about array")
m = np.array([[1,2,3],[1,2,3]])
n = np.array([[4,5,6],[4,5,6]])
print(m)
print()
print(n)
print(m+n)

We are talking about matrix
[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]
[[5 7 9]
 [5 7 9]]
We are talking about array
[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]
[[5 7 9]
 [5 7 9]]


In [5]:
print("We are talking about matrix")
a = np.matrix([[1,2,3],[1,2,3]])
c = np.matrix([[4,5,6],[4,5,6]])
print(a)
print()
print(c)
print(a-c)
print("We are talking about array")
m = np.array([[1,2,3],[1,2,3]])
n = np.array([[4,5,6],[4,5,6]])
print(m)
print()
print(n)
print(m-n)

We are talking about matrix
[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]
[[-3 -3 -3]
 [-3 -3 -3]]
We are talking about array
[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]
[[-3 -3 -3]
 [-3 -3 -3]]


In [7]:
print("We are talking about matrix")
a = np.matrix([[1,2],[3,4]])
c = np.matrix([[5,6],[7,8]])
print(a)
print()
print(c)
l = a.dot(c)
print(l)
print("We are talking about array")
m = np.array([[1,2],[3,4]])
n = np.array([[5,6],[7,8]])
print(m)
print()
print(n)
print(m*n)

We are talking about matrix
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
We are talking about array
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]


In [8]:
print("We are talking about matrix")
a = np.matrix([[1,2],[3,4]])
c = np.matrix([[5,6],[7,8]])
print(a)
print()
print(c)
print(a/c)
print("We are talking about array")
m = np.array([[1,2],[3,4]])
n = np.array([[5,6],[7,8]])
print(m)
print()
print(n)
print(m/n)

We are talking about matrix
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
We are talking about array
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


# Matrix Functions

Transpose function

In [9]:
a = np.matrix([[4,5,6],[14,16,18],[9,17,9]])
print(a)
print()
print(np.transpose(a))

[[ 4  5  6]
 [14 16 18]
 [ 9 17  9]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18  9]]


In [10]:
a = np.matrix([[4,5,6],[14,16,18],[9,17,9]])
print(a)
print()
print(a.T)

[[ 4  5  6]
 [14 16 18]
 [ 9 17  9]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18  9]]


Swapaxes function

In [11]:
a = np.matrix([[4,5,6],[14,16,18],[9,17,9]])
print(a)
print()
print(np.swapaxes(a,1,0))

[[ 4  5  6]
 [14 16 18]
 [ 9 17  9]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18  9]]


In [12]:
a = np.matrix([[4,5,6],[14,16,18],[9,17,9]])
print(a)
print()
print(np.swapaxes(a,0,1))

[[ 4  5  6]
 [14 16 18]
 [ 9 17  9]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18  9]]


Inverse

In [13]:
a = np.matrix([[3,4],[2,1]])
print(a)
print()
print(np.linalg.inv(a))

[[3 4]
 [2 1]]

[[-0.2  0.8]
 [ 0.4 -0.6]]


Power

In [16]:
a = np.matrix([[1,2],[4,5]])
print(a)
print()
print(np.linalg.matrix_power(a,2))
print()
print(np.linalg.matrix_power(a,0))
print()
print(np.linalg.matrix_power(a,-2))

[[1 2]
 [4 5]]

[[ 9 12]
 [24 33]]

[[1 0]
 [0 1]]

[[ 3.66666667 -1.33333333]
 [-2.66666667  1.        ]]


Determinate

In [20]:
a = np.matrix([[1,3,5],[2,4,6],[10,11,12]])
print(a)
print()
print(np.linalg.det(a))

[[ 1  3  5]
 [ 2  4  6]
 [10 11 12]]

0.0
