# Data Types in numpy

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
print("The data type is:", x.dtype)

The data type is: int32


In [3]:
x1 = np.array([2.5,3.5,3.7, 6.7,5.8,4.9])
print("The data type is:", x1.dtype)

The data type is: float64


In [4]:
x2 = np.array(["apple", "dog", "horse", "cat"])
print("The data type is:", x2.dtype)

The data type is: <U5


In [6]:
x3 = np.array(["apple", "dog", "horse", "cat", 4,5,6,7,3])
print("The data type is:", x3.dtype)

The data type is: <U11


# converting one data type into another data type

In [8]:
x = np.array([1,2,3,4,5])
print(x)
print(x.dtype)

x1 = np.array([1,2,3,4,5], dtype=np.int16)
print(x1)
print(x1.dtype)

[1 2 3 4 5]
int32
[1 2 3 4 5]
int16


In [9]:
x = np.array([1,2,3,4,5])
print(x)
print(x.dtype)

x1 = np.array([1,2,3,4,5], dtype="f")
print(x1)
print(x1.dtype)

[1 2 3 4 5]
int32
[1. 2. 3. 4. 5.]
float32


In [12]:
m = np.array([1,2,3,4])
print(m)
print(m.dtype)

m1 = np.float64(m)
print(m1)
print(m1.dtype)

[1 2 3 4]
int32
[1. 2. 3. 4.]
float64


In [13]:
m = np.array([1,2,3,4])
print(m)
print(m.dtype)

m1 = np.float64(m)
print(m1)
print(m1.dtype)

m2 = np.int64(m1)
print(m2)
print(m2.dtype)

[1 2 3 4]
int32
[1. 2. 3. 4.]
float64
[1 2 3 4]
int64


In [15]:
x = np.array([4.5,5.7,6.7,7.3,8.7])
y = x.astype(complex)
print(x)
print(x.dtype)
print(y)
print(y.dtype)

[4.5 5.7 6.7 7.3 8.7]
float64
[4.5+0.j 5.7+0.j 6.7+0.j 7.3+0.j 8.7+0.j]
complex128


# Arithmetic Operations in numpy array

Addition

In [20]:
x = np.array([1,2,3,4,5])
y = x+3
print(y)

[4 5 6 7 8]


In [21]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
z = x+y
print(z)

[ 6  8 10 12 14]


In [22]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
z = np.add(x,y)
print(z)

[ 6  8 10 12 14]


Subtraction

In [23]:
x = np.array([1,2,3,4,5])
y = x-2
print(y)

[-1  0  1  2  3]


In [25]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
z = y-x
print(z)

[4 4 4 4 4]


In [26]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
z = np.subtract(x,y)
print(z)

[-4 -4 -4 -4 -4]


Multiplication

In [27]:
x = np.array([1,2,3,4,5])
y = x*2
print(y)

[ 2  4  6  8 10]


In [28]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
z = y*x
print(z)

[ 5 12 21 32 45]


In [33]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
z = np.multiply(x,y)
print(z)

[ 5 12 21 32 45]


Division

In [34]:
x = np.array([1,2,3,4,5])
y = x/3
print(y)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [35]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
z = y/x
print(z)

[5.         3.         2.33333333 2.         1.8       ]


In [36]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
z = np.divide(x,y)
print(z)

[0.2        0.33333333 0.42857143 0.5        0.55555556]


Modulous

In [37]:
x = np.array([10,20,30,40,50])
y = x%3
print(y)

[1 2 0 1 2]


In [41]:
x = np.array([16,12,43,45,54])
y = np.array([5,6,7,8,9])
z = y%x
print(z)

[5 6 7 8 9]


In [42]:
x = np.array([16,23,33,45,54])
y = np.array([5,6,7,8,9])
z = np.mod(x,y)
print(z)

[1 5 5 5 0]


Reciprocal

In [44]:
a = np.array([23,25,28,30])
b = np.reciprocal(a)
print(b)

[0 0 0 0]


# Arithmentic Operations in 2d arrays

In [45]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])
x = n1+n2
print(x)

[[ 2  4  6  8]
 [10 12 14 16]]


In [46]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])
x = n1-n2
print(x)

[[0 0 0 0]
 [0 0 0 0]]


In [47]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])
x = n1*n2
print(x)

[[ 1  4  9 16]
 [25 36 49 64]]


In [48]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n2 = np.array([[1,2,3,4],[5,6,7,8]])
x = n1/n2
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Arithmentic Operations on 3d arrays

In [49]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[[1,2,3,4],[5,6,7,8]]])
x = n1+n2
print(x)
print(x.ndim)

[[[ 2  4  6  8]
  [10 12 14 16]]]
3


In [50]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[[1,2,3,4],[5,6,7,8]]])
x = n1-n2
print(x)
print(x.ndim)

[[[0 0 0 0]
  [0 0 0 0]]]
3


In [51]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[[1,2,3,4],[5,6,7,8]]])
x = n1*n2
print(x)
print(x.ndim)

[[[ 1  4  9 16]
  [25 36 49 64]]]
3


In [52]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[[1,2,3,4],[5,6,7,8]]])
x = n1/n2
print(x)
print(x.ndim)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3


# Arithmetic Functions

max & min along with index number

In [53]:
a = np.array([12,13,14,15,16,17,56,87,83])
print(np.max(a))
print(np.min(a))

87
12


In [55]:
a = np.array([12,13,14,15,16,17,56,87,83])
print(np.max(a), np.argmax(a))
print(np.min(a), np.argmin(a))

87 7
12 0


In [57]:
m = np.array([[34,24,45,67,68],[32,49,21,37,12]])
print(m)
print(m.ndim)
n = np.min(m, axis=0) # 0 - row
print(n)

[[34 24 45 67 68]
 [32 49 21 37 12]]
2
[32 24 21 37 12]


In [58]:
m = np.array([[34,24,45,67,68],[32,49,21,37,12]])
print(m)
print(m.ndim)
n = np.min(m, axis=1) # 1 - col
print(n)

[[34 24 45 67 68]
 [32 49 21 37 12]]
2
[24 12]


In [59]:
m = np.array([[34,24,45,67,68],[32,49,21,37,12]])
print(m)
print(m.ndim)
n = np.max(m, axis=0) # 0 - row
print(n)

[[34 24 45 67 68]
 [32 49 21 37 12]]
2
[34 49 45 67 68]


In [60]:
m = np.array([[34,24,45,67,68],[32,49,21,37,12]])
print(m)
print(m.ndim)
n = np.max(m, axis=1) # 1 - col
print(n)

[[34 24 45 67 68]
 [32 49 21 37 12]]
2
[68 49]


# Square root

In [61]:
a = np.array([12,13,14,45])
print(np.sqrt(a))

[3.46410162 3.60555128 3.74165739 6.70820393]


In [62]:
a = np.array([4,9,16,25])
print(np.sqrt(a))

[2. 3. 4. 5.]


In [64]:
a = np.array([[12,13,14,45,1],[9,64,81,25,13]])
print(np.sqrt(a))

[[3.46410162 3.60555128 3.74165739 6.70820393 1.        ]
 [3.         8.         9.         5.         3.60555128]]


sin value & cos value

In [65]:
a = np.array([1,2,3])
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


In [67]:
a = np.array([[1,2,3],[4,5,6],[8,9,10]])
print(np.sin(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.98935825  0.41211849 -0.54402111]]


In [68]:
a = np.array([1,2,3])
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925 ]


In [69]:
a = np.array([[1,2,3],[4,5,6],[8,9,10]])
print(np.cos(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [-0.14550003 -0.91113026 -0.83907153]]


In [71]:
a = np.array([1,2,3])
print(np.tan(a))

[ 1.55740772 -2.18503986 -0.14254654]


In [72]:
a = np.array([[1,2,3],[4,5,6],[8,9,10]])
print(np.tan(a))

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [-6.79971146 -0.45231566  0.64836083]]


# cumsum function

In [73]:
a = np.array([1,2,3,4])
print(np.cumsum(a))

[ 1  3  6 10]


In [74]:
a = np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
print(np.cumsum(a))

[  1   3   6  10  15  21  28  36  45  55  56  58  61  65  70  76  83  91
 100 110]


# Broadcasting numpy array

In [76]:
n1 = np.array([1,2,3,4])
n2 = np.array([2,3,4])
print(n1.shape)
print(n2.shape)
x = n1+n2
print(x)

(4,)
(3,)


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [79]:
n1 = np.array([1,2,3,4])
print(n1)
print(n1.shape)

n2 = np.array([[2],[3],[4],[5]])
print(n2)
print(n2.shape)
x = n1+n2
print(x)

[1 2 3 4]
(4,)
[[2]
 [3]
 [4]
 [5]]
(4, 1)
[[3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]


In [83]:
x = np.array([[4],[3]])
print(x.shape)
print(x)
y = np.array([[6,7,4],[1,3,2]])
print(y.shape)
print(y)
print()

print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)

(2, 1)
[[4]
 [3]]
(2, 3)
[[6 7 4]
 [1 3 2]]

[[10 11  8]
 [ 4  6  5]]

[[-2 -3  0]
 [ 2  0  1]]

[[24 28 16]
 [ 3  9  6]]

[[0.66666667 0.57142857 1.        ]
 [3.         1.         1.5       ]]


In [86]:
x = np.array([[4],[3],[5]])
print(x.shape)
print(x)
y = np.array([[6,7,7],[1,3,8],[4,5,7]])
print(y.shape)
print(y)
print()

print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)

(3, 1)
[[4]
 [3]
 [5]]
(3, 3)
[[6 7 7]
 [1 3 8]
 [4 5 7]]

[[10 11 11]
 [ 4  6 11]
 [ 9 10 12]]

[[-2 -3 -3]
 [ 2  0 -5]
 [ 1  0 -2]]

[[24 28 28]
 [ 3  9 24]
 [20 25 35]]

[[0.66666667 0.57142857 0.57142857]
 [3.         1.         0.375     ]
 [1.25       1.         0.71428571]]


In [87]:
x = np.array([[4,5,3],[1,3,4],[5,2,6]])
print(x.shape)
print(x)
y = np.array([[6,7,7],[1,3,8],[4,5,7]])
print(y.shape)
print(y)
print()

print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)

(3, 3)
[[4 5 3]
 [1 3 4]
 [5 2 6]]
(3, 3)
[[6 7 7]
 [1 3 8]
 [4 5 7]]

[[10 12 10]
 [ 2  6 12]
 [ 9  7 13]]

[[-2 -2 -4]
 [ 0  0 -4]
 [ 1 -3 -1]]

[[24 35 21]
 [ 1  9 32]
 [20 10 42]]

[[0.66666667 0.71428571 0.42857143]
 [1.         1.         0.5       ]
 [1.25       0.4        0.85714286]]
