# Unit 1 - Numpy

In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,5,6])
print(x)
print(type(x))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
l = [1,2,3,4,5,6]
print(l)
print(type(l))

[1, 2, 3, 4, 5, 6]
<class 'list'>


# Array is faster than list

In [5]:
%timeit [i**5 for i in range(1,10)]

The slowest run took 15.73 times longer than the fastest. This could mean that an intermediate result is being cached.
8.95 μs ± 14.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
%timeit np.arange(1,10)**5

44.8 μs ± 4.7 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# Creating numpy arrays

In [7]:
import numpy as np
x = np.array([1,6,7])
print(x)

[1 6 7]


In [8]:
x = np.array([56,79,409])
print(x)
print(type(x))
print(x.ndim)

[ 56  79 409]
<class 'numpy.ndarray'>
1


In [9]:
x = np.array([[56,79,409]])
print(x)
print(type(x))
print(x.ndim)

[[ 56  79 409]]
<class 'numpy.ndarray'>
2


In [10]:
x = np.array([[[56,79,409]]])
print(x)
print(type(x))
print(x.ndim)

[[[ 56  79 409]]]
<class 'numpy.ndarray'>
3


In [11]:
m = []
for i in range(1,5):
    num = input("enter number")
    m.append(num)

y = np.array(m)
print(y)
print(type(y))

enter number 56
enter number 78
enter number 0
enter number 5


['56' '78' '0' '5']
<class 'numpy.ndarray'>


# Creating 2d array

In [12]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8], 
                 [10,11,12,13]])
print(arr2)
print(arr2.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]
2


In [13]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8], 
                 [10,11,12,135]])
print(arr2)
print(arr2.ndim)

[[  1   2   3   4]
 [  5   6   7   8]
 [ 10  11  12 135]]
2


In [14]:
arr2 = np.array([[1,2,3,4,5,6,],
                 [5,6,7,8,9,10], 
                 [10,11,12,13,56,34]])
print(arr2)
print(arr2.ndim)

[[ 1  2  3  4  5  6]
 [ 5  6  7  8  9 10]
 [10 11 12 13 56 34]]
2


# Creating 3d array

In [15]:
arr3 = np.array([[[1,2,3,4],
                  [4,5,6,7],
                  [7,8,9,10]]])
print(arr3)
print(arr3.ndim)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]]
3


# Creating a multi dimensional array

In [16]:
arm = np.array([1,2,3,4], ndmin = 15)
print(arm)
print(arm.ndim)

[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]
15


In [17]:
arm = np.array(([1,2,3,4],[4,5,6,7]), ndmin = 25)
print(arm)
print(arm.ndim)

[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4]
                        [4 5 6 7]]]]]]]]]]]]]]]]]]]]]]]]]
25


# Numpy array with all its elements values are zeros

In [18]:
ar = np.zeros(5)
print(ar)
print(ar.ndim)

[0. 0. 0. 0. 0.]
1


In [19]:
ar1 = np.zeros((4,3))
print(ar1)
print(ar1.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


In [20]:
ar2 = np.zeros((2,3,4))
print(ar2)
print(ar2.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


# Numpy array all its elements with 1's

In [21]:
arr = np.ones(5)
print(arr)
print(arr.ndim)

[1. 1. 1. 1. 1.]
1


In [22]:
arr1 = np.ones((4,5))
print(arr1)
print(arr1.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2


In [23]:
arr2 = np.ones((1,3,3))
print(arr2)
print(arr2.ndim)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
3


In [24]:
arr2 = np.ones((2,3,3), dtype="bool")
print(arr2)
print("The dimension is:",arr2.ndim)

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
The dimension is: 3


# Creating an empty array

In [25]:
k = np.empty(3)
print(k)
print(k.ndim)

[0. 0. 0.]
1


In [26]:
d = np.empty((3,3), dtype="bool")
print(d)
print(d.ndim)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
2


In [27]:
d = np.empty((6,3))
print(d)
print(d.ndim)

[[9.53475865e-312 4.94065646e-322 0.00000000e+000]
 [0.00000000e+000 9.34603678e-307 1.16095484e-028]
 [3.74168445e+233 1.35717430e+131 1.74215252e-076]
 [8.82142681e+199 3.77075691e+233 6.32278327e+233]
 [3.77075633e+233 5.50693879e+222 2.59027849e-144]
 [4.82412328e+228 1.04718130e-142 1.03794806e-314]]
2


# Creating an array with range

In [28]:
b = np.arange(1,21)
print(b)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1


In [29]:
b = np.arange(3,101)
print(b)
print(b.ndim)

[  3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56
  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74
  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
  93  94  95  96  97  98  99 100]
1


In [30]:
b = np.arange(5,1001,5)
print(b)
print(b.ndim)

[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140
  145  150  155  160  165  170  175  180  185  190  195  200  205  210
  215  220  225  230  235  240  245  250  255  260  265  270  275  280
  285  290  295  300  305  310  315  320  325  330  335  340  345  350
  355  360  365  370  375  380  385  390  395  400  405  410  415  420
  425  430  435  440  445  450  455  460  465  470  475  480  485  490
  495  500  505  510  515  520  525  530  535  540  545  550  555  560
  565  570  575  580  585  590  595  600  605  610  615  620  625  630
  635  640  645  650  655  660  665  670  675  680  685  690  695  700
  705  710  715  720  725  730  735  740  745  750  755  760  765  770
  775  780  785  790  795  800  805  810  815  820  825  830  835  840
  845  850  855  860  865  870  875  880  885  890  895  900  905  910
  915  920  925  930  935  940  945  950  955  960  965  970  975  980
  985 

# linspace

In [31]:
a = np.linspace(1,10,5)
print(a)
print(a.ndim)

[ 1.    3.25  5.5   7.75 10.  ]
1


In [32]:
a = np.linspace(1,30,8)
print(a)
print(a.ndim)

[ 1.          5.14285714  9.28571429 13.42857143 17.57142857 21.71428571
 25.85714286 30.        ]
1


In [33]:
a = np.linspace(5,20,6)
print(a)
print(a.ndim)

[ 5.  8. 11. 14. 17. 20.]
1


# Shape 

In [34]:
ar = np.array([[1,2,3], [10,20,25]])
print(ar)
print(ar.ndim)
print(ar.shape)

[[ 1  2  3]
 [10 20 25]]
2
(2, 3)


In [36]:
ar = np.array([[[1,2,3], [10,20,25], [45,34,23], [56,76,8]]])
print(ar)
print(ar.ndim)
print(ar.shape)

[[[ 1  2  3]
  [10 20 25]
  [45 34 23]
  [56 76  8]]]
3
(1, 4, 3)


# reshape

In [39]:
m = np.array([1,2,3,4,5,6,7,8,9,10])
n = m.reshape(2,5)
print(n)
print()
print(m)
print()
print(n.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 1  2  3  4  5  6  7  8  9 10]

2


In [43]:
m = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
n = m.reshape(4,4)
print(n)
print()
print(m)
print()
print(n.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

2


In [45]:
m = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
n = m.reshape(3,4)
print(n)
print()
print(m)
print()
print(n.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

2
